/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;

/**
 *
 * @author alunoces
 */
public class T_principal extends javax.swing.JFrame {

    /**
     * Creates new form T_principal
     */
    public T_principal() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.gray);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        mmCadrastro = new javax.swing.JMenu();
        mmAluno = new javax.swing.JMenuItem();
        mmCurso = new javax.swing.JMenuItem();
        mmProfessor = new javax.swing.JMenuItem();
        mmDisiciplina = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mmSair = new javax.swing.JMenuItem();
        mmEdição = new javax.swing.JMenu();
        mmRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        mmCadrastro.setMnemonic('c');
        mmCadrastro.setText("Cadrastro");

        mmAluno.setMnemonic('a');
        mmAluno.setText("Aluno");
        mmAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmAlunoActionPerformed(evt);
            }
        });
        mmCadrastro.add(mmAluno);

        mmCurso.setMnemonic('c');
        mmCurso.setText("Curso");
        mmCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmCursoActionPerformed(evt);
            }
        });
        mmCadrastro.add(mmCurso);

        mmProfessor.setMnemonic('p');
        mmProfessor.setText("Professor");
        mmProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmProfessorActionPerformed(evt);
            }
        });
        mmCadrastro.add(mmProfessor);

        mmDisiciplina.setMnemonic('d');
        mmDisiciplina.setText("Disciplina");
        mmDisiciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmDisiciplinaActionPerformed(evt);
            }
        });
        mmCadrastro.add(mmDisiciplina);
        mmCadrastro.add(jSeparator1);

        mmSair.setMnemonic('s');
        mmSair.setText("Sair");
        mmCadrastro.add(mmSair);

        jMenuBar2.add(mmCadrastro);

        mmEdição.setMnemonic('e');
        mmEdição.setText("Edição");
        jMenuBar2.add(mmEdição);

        mmRelatorio.setMnemonic('r');
        mmRelatorio.setText("Relatorio");
        jMenuBar2.add(mmRelatorio);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmAlunoActionPerformed
        // TODO add your handling code here:
        new Aluno(null,true).setVisible(true);
    }//GEN-LAST:event_mmAlunoActionPerformed

    private void mmCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmCursoActionPerformed
        // TODO add your handling code here:
        new Curso(null, true).setVisible(true);
    }//GEN-LAST:event_mmCursoActionPerformed

    private void mmProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmProfessorActionPerformed
        // TODO add your handling code here:
        new Professor(null, true).setVisible(true);
    }//GEN-LAST:event_mmProfessorActionPerformed

    private void mmDisiciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmDisiciplinaActionPerformed
       // TODO add your handling code here:
       new Disciplina(null, true).setVisible(true);
    }//GEN-LAST:event_mmDisiciplinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mmAluno;
    private javax.swing.JMenu mmCadrastro;
    private javax.swing.JMenuItem mmCurso;
    private javax.swing.JMenuItem mmDisiciplina;
    private javax.swing.JMenu mmEdição;
    private javax.swing.JMenuItem mmProfessor;
    private javax.swing.JMenu mmRelatorio;
    private javax.swing.JMenuItem mmSair;
    // End of variables declaration//GEN-END:variables
}
